### ISSUE TITLE
Will you provide the annotated dataset?

### ISSUE THREAD

**Issue by MiladAlshomary** [chridey/fixedthat#8]
Hi,

I am interested in your work and wondering if you will provide any time soon the annotated data and some documentation on how to use your code?

Regards,

**Comment by chridey** [comment]
Thanks for your interest in our work and my apologies for the late reply (I recently graduated). I'm not able to post the data publicly (unfortunately due to the IRB) but please e-mail me directly and I will share with you the Google drive link.

Best,
Chris

**Comment by MiladAlshomary** [comment]
Thanks for your response and congratulation!

**Comment by benjpau** [comment]
@chridey Hi! I am also interested in the data, could you send it to me, too? Thanks!
